-- UPI DIGITAL PAYMENTS ANALYSIS 

-- Project: UPI Digital Payments Analysis
-- Tools: MySQL
-- Dataset Size: 2,50,000 Transactions
-- Objective: Analyze UPI digital payment transactions to understand transaction patterns, bank performance, fraud trends, and customer spending behavior.


-- 1. DATABASE SETUP

CREATE DATABASE UPI_PAYMENTS_ANALYSIS;
USE UPI_PAYMENTS_ANALYSIS;


-- 2. DATA EXPLORATION 

-- Q1. PREVIEW THE DATASET
SELECT * FROM UPI_TRANSACTIONS LIMIT 10;

-- Q2. TOTAL NUMBER OF TRANSACTIONS
SELECT COUNT(*) AS TOTAL_TRANSACTIONS FROM UPI_TRANSACTIONS;

-- Q3. TOTAL NUMBER OF COLUMNS
SELECT COUNT(*) AS TOTAL_COLUMNS
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'UPI_PAYMENTS_ANALYSIS'
  AND TABLE_NAME = 'UPI_TRANSACTIONS';

-- Q4. DATASET TIME PERIOD
SELECT MIN(`TIMESTAMP`) AS START_DATE,
       MAX(`TIMESTAMP`) AS END_DATE,
       DATEDIFF(MAX(`TIMESTAMP`), MIN(`TIMESTAMP`)) AS DAYS_COVERED
FROM UPI_TRANSACTIONS;

-- Q5. DISTINCT SENDER BANKS
SELECT COUNT(DISTINCT sender_bank) AS TOTAL_SENDER_BANKS FROM UPI_TRANSACTIONS;

-- Q6. DISTINCT RECEIVER BANKS
SELECT COUNT(DISTINCT RECEIVER_bank) AS TOTAL_RECEIVER_BANKS FROM UPI_TRANSACTIONS;

-- Q7. DISTINCT MERCHANT CATEGORIES
SELECT COUNT(DISTINCT MERCHANT_CATEGORY) AS TOTAL_MERCHANT_CATEGORY FROM UPI_TRANSACTIONS;

-- Q8. DISTINCT STATES
SELECT COUNT(DISTINCT sender_STATE) AS TOTAL_SENDER_STATE FROM UPI_TRANSACTIONS;

-- Q9. TRANSACTION STATUS DISTRIBUTION
SELECT TRANSACTION_STATUS,
       COUNT(*) AS TXN_COUNT,
       ROUND(COUNT(*) * 100.0 / (SELECT COUNT(*) FROM UPI_TRANSACTIONS), 2) AS PCT
FROM UPI_TRANSACTIONS
GROUP BY TRANSACTION_STATUS;

-- Q10. FRAUD VS NON-FRAUD TRANSACTIONS
SELECT CASE WHEN FRAUD_FLAG = 1 THEN 'FRAUD' ELSE 'NON-FRAUD' END AS TXN_CLASS,
       COUNT(*) AS TXN_COUNT,
       ROUND(COUNT(*) * 100.0 / (SELECT COUNT(*) FROM UPI_TRANSACTIONS), 4) AS PCT
FROM UPI_TRANSACTIONS
GROUP BY TXN_CLASS;


-- 3. DATA QUALITY ASSESSMENT & CLEANING 

-- Q11. CHECK NULL VALUES 
SELECT
    SUM(`TRANSACTION ID` IS NULL)          AS NULL_TXN_ID,
    SUM(`TIMESTAMP` IS NULL)               AS NULL_TIMESTAMP,
    SUM(`TRANSACTION TYPE` IS NULL)        AS NULL_TXN_TYPE,
    SUM(MERCHANT_CATEGORY IS NULL)         AS NULL_CATEGORY,
    SUM(`AMOUNT (INR)` IS NULL)            AS NULL_AMOUNT,
    SUM(TRANSACTION_STATUS IS NULL)        AS NULL_STATUS,
    SUM(SENDER_AGE_GROUP IS NULL)          AS NULL_SENDER_AGE,
    SUM(RECEIVER_AGE_GROUP IS NULL)        AS NULL_RECEIVER_AGE,
    SUM(SENDER_STATE IS NULL)              AS NULL_STATE,
    SUM(SENDER_BANK IS NULL)               AS NULL_SENDER_BANK,
    SUM(RECEIVER_BANK IS NULL)             AS NULL_RECEIVER_BANK,
    SUM(DEVICE_TYPE IS NULL)               AS NULL_DEVICE,
    SUM(NETWORK_TYPE IS NULL)              AS NULL_NETWORK,
    SUM(FRAUD_FLAG IS NULL)                AS NULL_FRAUD_FLAG,
    SUM(HOUR_OF_DAY IS NULL)               AS NULL_HOUR,
    SUM(DAY_OF_WEEK IS NULL)               AS NULL_DAY_OF_WEEK
FROM UPI_TRANSACTIONS;

-- Q12. CHECK DUPLICATE TRANSACTION IDS
SELECT `TRANSACTION ID`, COUNT(*) AS OCCURRENCES
FROM UPI_TRANSACTIONS
GROUP BY `TRANSACTION ID`
HAVING COUNT(*) > 1;

-- Q13. CHECK DUPLICATE COMPLETE RECORDS 
WITH RANKED AS (
    SELECT `TRANSACTION ID`,
           ROW_NUMBER() OVER (
               PARTITION BY `TIMESTAMP`, `TRANSACTION TYPE`, MERCHANT_CATEGORY,
                            `AMOUNT (INR)`, TRANSACTION_STATUS, SENDER_BANK,
                            RECEIVER_BANK, SENDER_STATE
               ORDER BY `TRANSACTION ID`
           ) AS RN
    FROM UPI_TRANSACTIONS
)
SELECT COUNT(*) AS FULL_DUPLICATE_ROWS
FROM RANKED
WHERE RN > 1;

-- Q14. CHECK NEGATIVE TRANSACTION AMOUNTS
SELECT COUNT(*) AS NEGATIVE_AMOUNT_ROWS
FROM UPI_TRANSACTIONS
WHERE `AMOUNT (INR)` < 0;

-- Q15. CHECK ZERO-VALUE TRANSACTIONS
SELECT COUNT(*) AS ZERO_AMOUNT_ROWS
FROM UPI_TRANSACTIONS
WHERE `AMOUNT (INR)` = 0;

-- Q16. CHECK INVALID HOUR VALUES (MUST BE 0–23)
SELECT COUNT(*) AS INVALID_HOUR_ROWS
FROM UPI_TRANSACTIONS
WHERE HOUR_OF_DAY NOT BETWEEN 0 AND 23;

-- Q17. CHECK INVALID FRAUD FLAG VALUES (MUST BE 0 OR 1)
SELECT COUNT(*) AS INVALID_FRAUD_FLAG_ROWS
FROM UPI_TRANSACTIONS
WHERE FRAUD_FLAG NOT IN (0, 1);

-- Q18. CHECK BLANK MERCHANT CATEGORIES
SELECT COUNT(*) AS BLANK_MERCHANT_CATEGORY_ROWS
FROM UPI_TRANSACTIONS
WHERE MERCHANT_CATEGORY IS NULL OR TRIM(MERCHANT_CATEGORY) = '';

-- Q19. STANDARDIZE TRANSACTION STATUS (UPPERCASE, TRIMMED, IN PLACE)
SELECT DISTINCT TRANSACTION_STATUS FROM UPI_TRANSACTIONS;

UPDATE UPI_TRANSACTIONS
SET TRANSACTION_STATUS = UPPER(TRIM(TRANSACTION_STATUS));

-- VERIFY STANDARDIZATION
SELECT DISTINCT TRANSACTION_STATUS FROM UPI_TRANSACTIONS;

-- Q20. TRIM WHITESPACE FROM TEXT COLUMNS (IN PLACE)
SELECT DISTINCT MERCHANT_CATEGORY FROM UPI_TRANSACTIONS;

UPDATE UPI_TRANSACTIONS
SET `TRANSACTION TYPE`   = TRIM(`TRANSACTION TYPE`),
    MERCHANT_CATEGORY    = TRIM(MERCHANT_CATEGORY),
    SENDER_AGE_GROUP     = TRIM(SENDER_AGE_GROUP),
    RECEIVER_AGE_GROUP   = TRIM(RECEIVER_AGE_GROUP),
    SENDER_STATE          = TRIM(SENDER_STATE),
    SENDER_BANK            = TRIM(SENDER_BANK),
    RECEIVER_BANK           = TRIM(RECEIVER_BANK),
    DEVICE_TYPE              = TRIM(DEVICE_TYPE),
    NETWORK_TYPE              = TRIM(NETWORK_TYPE),
    DAY_OF_WEEK                = TRIM(DAY_OF_WEEK);

-- VERIFY DATA AFTER TRIMMING
SELECT DISTINCT MERCHANT_CATEGORY FROM UPI_TRANSACTIONS;


-- 4. EXPLORATORY DATA ANALYSIS 

-- Q21. TRANSACTION VOLUME BY STATE
SELECT
    SENDER_STATE,
    COUNT(*) AS TXN_COUNT,
    ROUND(SUM(`AMOUNT (INR)`), 2) AS TOTAL_VALUE,
    ROUND(AVG(`AMOUNT (INR)`), 2) AS AVG_VALUE
FROM UPI_TRANSACTIONS
GROUP BY SENDER_STATE
ORDER BY TOTAL_VALUE DESC;

-- Q22. TRANSACTION VOLUME BY MERCHANT CATEGORY
SELECT
    MERCHANT_CATEGORY,
    COUNT(*) AS TXN_COUNT,
    ROUND(SUM(`AMOUNT (INR)`), 2) AS TOTAL_VALUE,
    ROUND(AVG(`AMOUNT (INR)`), 2) AS AVG_VALUE
FROM UPI_TRANSACTIONS
GROUP BY MERCHANT_CATEGORY
ORDER BY TOTAL_VALUE DESC;

-- Q23. TRANSACTION VOLUME BY SENDER BANK
SELECT
    SENDER_BANK,
    COUNT(*) AS TXN_COUNT,
    ROUND(SUM(`AMOUNT (INR)`), 2) AS TOTAL_VALUE,
    ROUND(AVG(`AMOUNT (INR)`), 2) AS AVG_VALUE
FROM UPI_TRANSACTIONS
GROUP BY SENDER_BANK
ORDER BY TOTAL_VALUE DESC;

-- Q24. TRANSACTION VOLUME BY RECEIVER BANK
SELECT
    RECEIVER_BANK,
    COUNT(*) AS TXN_COUNT,
    ROUND(SUM(`AMOUNT (INR)`), 2) AS TOTAL_VALUE,
    ROUND(AVG(`AMOUNT (INR)`), 2) AS AVG_VALUE
FROM UPI_TRANSACTIONS
GROUP BY RECEIVER_BANK
ORDER BY TOTAL_VALUE DESC;

-- Q25. TRANSACTION TYPE DISTRIBUTION
SELECT `TRANSACTION TYPE`,
       COUNT(*) AS TXN_COUNT,
       ROUND(COUNT(*) * 100.0 / (SELECT COUNT(*) FROM UPI_TRANSACTIONS), 2) AS PCT
FROM UPI_TRANSACTIONS
GROUP BY `TRANSACTION TYPE`
ORDER BY TXN_COUNT DESC;

-- Q26. DEVICE TYPE DISTRIBUTION
SELECT DEVICE_TYPE,
       COUNT(*) AS TXN_COUNT,
       ROUND(COUNT(*) * 100.0 / (SELECT COUNT(*) FROM UPI_TRANSACTIONS), 2) AS PCT
FROM UPI_TRANSACTIONS
GROUP BY DEVICE_TYPE
ORDER BY TXN_COUNT DESC;

-- Q27. NETWORK TYPE DISTRIBUTION
SELECT NETWORK_TYPE,
       COUNT(*) AS TXN_COUNT,
       ROUND(COUNT(*) * 100.0 / (SELECT COUNT(*) FROM UPI_TRANSACTIONS), 2) AS PCT
FROM UPI_TRANSACTIONS
GROUP BY NETWORK_TYPE
ORDER BY TXN_COUNT DESC;

-- Q28. SENDER AGE GROUP DISTRIBUTION
SELECT SENDER_AGE_GROUP,
       COUNT(*) AS TXN_COUNT,
       ROUND(COUNT(*) * 100.0 / (SELECT COUNT(*) FROM UPI_TRANSACTIONS), 2) AS PCT
FROM UPI_TRANSACTIONS
GROUP BY SENDER_AGE_GROUP
ORDER BY TXN_COUNT DESC;

-- Q29. HOUR-WISE TRANSACTION TREND
SELECT
    HOUR_OF_DAY,
    COUNT(*) AS TXN_COUNT,
    ROUND(SUM(`AMOUNT (INR)`), 2) AS TOTAL_VALUE
FROM UPI_TRANSACTIONS
GROUP BY HOUR_OF_DAY
ORDER BY HOUR_OF_DAY;

-- Q30. WEEKEND VS WEEKDAY TRANSACTIONS
SELECT
    CASE
        WHEN IS_WEEKEND = 1 THEN 'WEEKEND'
        ELSE 'WEEKDAY'
    END AS DAY_TYPE,
    COUNT(*) AS TXN_COUNT,
    ROUND(COUNT(*) * 100.0 / (SELECT COUNT(*) FROM UPI_TRANSACTIONS), 2) AS PCT,
    ROUND(SUM(`AMOUNT (INR)`), 2) AS TOTAL_VALUE,
    ROUND(AVG(`AMOUNT (INR)`), 2) AS AVG_VALUE
FROM UPI_TRANSACTIONS
GROUP BY DAY_TYPE;

-- 5. BUSINESS ANALYSIS

-- Q31. TOP 10 MERCHANT CATEGORIES BY TRANSACTION VALUE
SELECT MERCHANT_CATEGORY,
       ROUND(SUM(`AMOUNT (INR)`), 2) AS TOTAL_VALUE
FROM UPI_TRANSACTIONS
GROUP BY MERCHANT_CATEGORY
ORDER BY TOTAL_VALUE DESC
LIMIT 10;

-- Q32. TOP SENDER BANKS BY TRANSACTION VALUE
SELECT SENDER_BANK,
       ROUND(SUM(`AMOUNT (INR)`), 2) AS TOTAL_VALUE
FROM UPI_TRANSACTIONS
GROUP BY SENDER_BANK
ORDER BY TOTAL_VALUE DESC;

-- Q33. BANKS WITH THE HIGHEST SUCCESSFUL TRANSACTIONS
SELECT SENDER_BANK,
       SUM(TRANSACTION_STATUS = 'SUCCESS') AS SUCCESSFUL_TXNS,
       COUNT(*) AS TOTAL_TXNS,
       ROUND(SUM(TRANSACTION_STATUS = 'SUCCESS') * 100.0 / COUNT(*), 2) AS SUCCESS_RATE_PCT
FROM UPI_TRANSACTIONS
GROUP BY SENDER_BANK
ORDER BY SUCCESSFUL_TXNS DESC;

-- Q34. AVERAGE TRANSACTION AMOUNT BY MERCHANT CATEGORY
SELECT MERCHANT_CATEGORY,
       ROUND(AVG(`AMOUNT (INR)`), 2) AS AVG_AMOUNT
FROM UPI_TRANSACTIONS
GROUP BY MERCHANT_CATEGORY
ORDER BY AVG_AMOUNT DESC;

-- Q35. FRAUD RATE BY STATE
SELECT SENDER_STATE,
       COUNT(*) AS TXN_COUNT,
       SUM(FRAUD_FLAG) AS FRAUD_COUNT,
       ROUND(SUM(FRAUD_FLAG) * 100.0 / COUNT(*), 4) AS FRAUD_RATE_PCT
FROM UPI_TRANSACTIONS
GROUP BY SENDER_STATE
ORDER BY FRAUD_RATE_PCT DESC;

-- Q36. FRAUD RATE BY MERCHANT CATEGORY
SELECT MERCHANT_CATEGORY,
       COUNT(*) AS TXN_COUNT,
       SUM(FRAUD_FLAG) AS FRAUD_COUNT,
       ROUND(SUM(FRAUD_FLAG) * 100.0 / COUNT(*), 4) AS FRAUD_RATE_PCT
FROM UPI_TRANSACTIONS
GROUP BY MERCHANT_CATEGORY
ORDER BY FRAUD_RATE_PCT DESC;

-- Q37. AVERAGE TRANSACTION AMOUNT BY SENDER AGE GROUP
SELECT SENDER_AGE_GROUP,
       ROUND(AVG(`AMOUNT (INR)`), 2) AS AVG_AMOUNT
FROM UPI_TRANSACTIONS
GROUP BY SENDER_AGE_GROUP
ORDER BY AVG_AMOUNT DESC;

-- Q38. PEAK TRANSACTION HOURS BASED ON TRANSACTION VALUE
SELECT HOUR_OF_DAY,
       ROUND(SUM(`AMOUNT (INR)`), 2) AS TOTAL_VALUE
FROM UPI_TRANSACTIONS
GROUP BY HOUR_OF_DAY
ORDER BY TOTAL_VALUE DESC
LIMIT 5;

-- Q39. STATES CONTRIBUTING THE HIGHEST TRANSACTION VALUE
SELECT SENDER_STATE,
       ROUND(SUM(`AMOUNT (INR)`), 2) AS TOTAL_VALUE
FROM UPI_TRANSACTIONS
GROUP BY SENDER_STATE
ORDER BY TOTAL_VALUE DESC
LIMIT 10;

-- Q40. WEEKEND VS WEEKDAY TRANSACTION VALUE
SELECT CASE WHEN IS_WEEKEND = 1 THEN 'WEEKEND' ELSE 'WEEKDAY' END AS DAY_TYPE,
       COUNT(*) AS TXN_COUNT,
       ROUND(SUM(`AMOUNT (INR)`), 2) AS TOTAL_VALUE,
       ROUND(AVG(`AMOUNT (INR)`), 2) AS AVG_VALUE
FROM UPI_TRANSACTIONS
GROUP BY DAY_TYPE;

-- Q41. DEVICE TYPE PERFORMANCE BASED ON SUCCESS RATE
SELECT DEVICE_TYPE,
       COUNT(*) AS TXN_COUNT,
       ROUND(SUM(TRANSACTION_STATUS = 'SUCCESS') * 100.0 / COUNT(*), 2) AS SUCCESS_RATE_PCT
FROM UPI_TRANSACTIONS
GROUP BY DEVICE_TYPE
ORDER BY SUCCESS_RATE_PCT DESC;

-- Q42. NETWORK TYPE PERFORMANCE BASED ON SUCCESS RATE
SELECT NETWORK_TYPE,
       COUNT(*) AS TXN_COUNT,
       ROUND(SUM(TRANSACTION_STATUS = 'SUCCESS') * 100.0 / COUNT(*), 2) AS SUCCESS_RATE_PCT
FROM UPI_TRANSACTIONS
GROUP BY NETWORK_TYPE
ORDER BY SUCCESS_RATE_PCT DESC;


-- 6. KEY BUSINESS INSIGHTS

-- 1. DATA QUALITY IS HIGH OUT OF THE BOX: 0 NULLS, 0 DUPLICATE
--    TRANSACTION IDS, 0 NEGATIVE/ZERO AMOUNTS, AND NO INVALID
--    HOUR_OF_DAY OR FRAUD_FLAG VALUES — Q11-Q18 ALL RETURN 0 ROWS.
-- 2. SBI DOMINATES ON BOTH VOLUME AND VALUE — IT LEADS EVERY BANK BY
--    TRANSACTION COUNT AND CONTRIBUTES ~₹82.8M IN TOTAL VALUE, ROUGHLY
--    ₹33M MORE THAN THE #2 BANK (HDFC, ~₹49.8M).
-- 3. BANK SUCCESS RATES ARE TIGHTLY CLUSTERED (94.9%-95.2%), SO
--    RELIABILITY ISN'T REALLY A DIFFERENTIATOR BETWEEN BANKS — THE
--    GAP BETWEEN THE BEST (HDFC) AND WORST (YES BANK) IS UNDER HALF A
--    PERCENTAGE POINT.
-- 4. SHOPPING IS THE BIGGEST VALUE DRIVER OVERALL (~₹76.9M TOTAL),
--    BUT EDUCATION HAS THE HIGHEST AVERAGE TICKET SIZE PER
--    TRANSACTION — HIGH-FREQUENCY CATEGORIES AND HIGH-VALUE
--    CATEGORIES ARE NOT THE SAME CATEGORIES.
-- 5. FRAUD IS RARE (480 OF 250,000 TRANSACTIONS, ~0.19%) AND SLIGHTLY
--    CONCENTRATED: KARNATAKA AND RAJASTHAN HAVE THE HIGHEST STATE-LEVEL
--    FRAUD RATES (~0.23%), AND TRANSPORT/EDUCATION HAVE THE HIGHEST
--    CATEGORY-LEVEL FRAUD RATES (~0.21%) DESPITE NOT BEING THE
--    HIGHEST-VALUE CATEGORIES.
-- 6. SPENDING PEAKS IN THE 36-45 AGE GROUP (~₹1,424 AVG/TXN) AND
--    DECLINES STEADILY FOR BOTH YOUNGER (18-25: ~₹1,195) AND OLDER
--    (56+: ~₹1,188) SENDERS.
-- 7. THE EVENING HOURS (18:00-20:00) DOMINATE BOTH TRANSACTION VOLUME
--    AND TOTAL VALUE, WITH HOUR 19 ALONE CONTRIBUTING ~₹28.2M — CAPACITY
--    AND FRAUD MONITORING SHOULD WEIGHT THIS WINDOW MORE HEAVILY.
-- 8. WEEKDAY VS WEEKEND BEHAVIOR IS NEARLY FLAT ON A PER-TRANSACTION
--    BASIS (AVG ~₹1,312 VS ~₹1,310) — WEEKENDS BRING LOWER VOLUME, NOT
--    MATERIALLY DIFFERENT SPENDING HABITS.


-- 7. BUSINESS RECOMMENDATIONS

-- 1. FOCUS RELIABILITY ENGINEERING ON CLOSING THE SMALL SUCCESS-RATE
--    GAP AT YES BANK/ICICI RATHER THAN TREATING IT AS A MAJOR OUTAGE
--    RISK — THE ABSOLUTE GAP VERSUS THE BEST PERFORMER IS SMALL BUT
--    CONSISTENT ENOUGH TO BE WORTH INVESTIGATING.
-- 2. SCALE INFRASTRUCTURE AND FRAUD-REVIEW STAFFING FOR THE
--    18:00-20:00 WINDOW SPECIFICALLY, SINCE IT'S THE SINGLE HEAVIEST
--    PERIOD FOR BOTH VOLUME AND RUPEE VALUE.
-- 3. APPLY TIGHTER FRAUD-DETECTION THRESHOLDS TO EDUCATION AND
--    TRANSPORT TRANSACTIONS — THEY COMBINE ABOVE-AVERAGE FRAUD RATES
--    WITH MEANINGFUL TRANSACTION VALUES, UNLIKE LOWER-FRAUD,
--    HIGH-VALUE CATEGORIES LIKE UTILITIES.
-- 4. RUN STATE-SPECIFIC FRAUD MONITORING FOR KARNATAKA AND RAJASTHAN
--    GIVEN THEIR CONSISTENTLY ELEVATED FRAUD RATES RELATIVE TO OTHER
--    HIGH-VOLUME STATES.
-- 5. DESIGN RETENTION OFFERS AROUND THE 36-45 AGE SEGMENT (HIGHEST
--    AVERAGE SPEND) WHILE USING ACQUISITION-STYLE INCENTIVES FOR THE
--    18-25 AND 56+ SEGMENTS, WHERE AVERAGE SPEND IS LOWER.
-- 6. TREAT WEEKEND DIPS AS A VOLUME PROBLEM, NOT A BEHAVIOR-CHANGE
--    PROBLEM — SINCE PER-TRANSACTION VALUE BARELY MOVES, WEEKEND
--    PROMOTIONS SHOULD AIM TO DRIVE MORE TRANSACTIONS RATHER THAN
--    BIGGER ONES.


